/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const ContactCreateLazyImport = createFileRoute('/contact/create')()
const ContactContactIdIndexLazyImport = createFileRoute(
  '/contact/$contactId/',
)()
const ContactContactIdEditLazyImport = createFileRoute(
  '/contact/$contactId/edit',
)()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const LogoutRoute = LogoutImport.update({
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ContactCreateLazyRoute = ContactCreateLazyImport.update({
  path: '/contact/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contact/create.lazy').then((d) => d.Route),
)

const ContactContactIdIndexLazyRoute = ContactContactIdIndexLazyImport.update({
  path: '/contact/$contactId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contact/$contactId/index.lazy').then((d) => d.Route),
)

const ContactContactIdEditLazyRoute = ContactContactIdEditLazyImport.update({
  path: '/contact/$contactId/edit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/contact/$contactId/edit.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact/create': {
      id: '/contact/create'
      path: '/contact/create'
      fullPath: '/contact/create'
      preLoaderRoute: typeof ContactCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact/$contactId/edit': {
      id: '/contact/$contactId/edit'
      path: '/contact/$contactId/edit'
      fullPath: '/contact/$contactId/edit'
      preLoaderRoute: typeof ContactContactIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/contact/$contactId/': {
      id: '/contact/$contactId/'
      path: '/contact/$contactId'
      fullPath: '/contact/$contactId'
      preLoaderRoute: typeof ContactContactIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LogoutRoute,
  LoginLazyRoute,
  RegisterLazyRoute,
  ContactCreateLazyRoute,
  ContactContactIdEditLazyRoute,
  ContactContactIdIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/logout",
        "/login",
        "/register",
        "/contact/create",
        "/contact/$contactId/edit",
        "/contact/$contactId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/logout": {
      "filePath": "logout.ts"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/register": {
      "filePath": "register.lazy.tsx"
    },
    "/contact/create": {
      "filePath": "contact/create.lazy.tsx"
    },
    "/contact/$contactId/edit": {
      "filePath": "contact/$contactId/edit.lazy.tsx"
    },
    "/contact/$contactId/": {
      "filePath": "contact/$contactId/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
